/**
 * Dane o miastach Polski dla systemu cenowego
 * Zawiera współczynniki, kategorię miasta, informacje o dzielnicach
 */

export type CityCategory = 'metropolis' | 'large' | 'medium' | 'small';

export interface WarszawaDistrict {
  id: string;
  name: string;
  polishName: string;
  coefficient: number; // współczynnik Wdzielnica
}

export interface CityData {
  id: string;
  name: string;
  slug: string;
  voivodeship: string;
  population: number;
  category: CityCategory;
  coefficient: number; // współczynnik Wmiejscowość
  districts?: WarszawaDistrict[];
}

// ============================================================================
// DZIELNICE WARSZAWY
// ============================================================================

const WARSAW_DISTRICTS: WarszawaDistrict[] = [
  { id: 'warszawa_mokotow', name: 'Mokotów', polishName: 'Mokotów', coefficient: 1.0 },
  { id: 'warszawa_srodmiescie', name: 'Śródmieście', polishName: 'Śródmieście', coefficient: 1.15 },
  { id: 'warszawa_wawer', name: 'Wawer', polishName: 'Wawer', coefficient: 0.92 },
  { id: 'warszawa_wlochy', name: 'Włochy', polishName: 'Włochy', coefficient: 0.95 },
  { id: 'warszawa_piaseczno', name: 'Piaseczno', polishName: 'Piaseczno', coefficient: 0.88 },
  { id: 'warszawa_praga_poludnie', name: 'Praga-Południe', polishName: 'Praga-Południe', coefficient: 0.98 },
  { id: 'warszawa_praga_polnoc', name: 'Praga-Północ', polishName: 'Praga-Północ', coefficient: 0.92 },
  { id: 'warszawa_zoliborz', name: 'Żoliborz', polishName: 'Żoliborz', coefficient: 1.05 },
  { id: 'warszawa_wola', name: 'Wola', polishName: 'Wola', coefficient: 1.02 },
  { id: 'warszawa_ochota', name: 'Ochota', polishName: 'Ochota', coefficient: 1.0 },
  { id: 'warszawa_bielany', name: 'Bielany', polishName: 'Bielany', coefficient: 0.98 },
  { id: 'warszawa_rembertow', name: 'Rembertów', polishName: 'Rembertów', coefficient: 0.85 },
];

// ============================================================================
// DZIELNICE KRAKOWA
// ============================================================================

const KRAKOW_DISTRICTS: WarszawaDistrict[] = [
  { id: 'krakow_stare_miasto', name: 'Stare Miasto', polishName: 'Stare Miasto', coefficient: 1.1 },
  { id: 'krakow_podgorze', name: 'Podgórze', polishName: 'Podgórze', coefficient: 0.95 },
  { id: 'krakow_nowa_huta', name: 'Nowa Huta', polishName: 'Nowa Huta', coefficient: 0.88 },
  { id: 'krakow_zwierzyniec', name: 'Zwierzyniec', polishName: 'Zwierzyniec', coefficient: 1.05 },
  { id: 'krakow_bronowice', name: 'Bronowice', polishName: 'Bronowice', coefficient: 0.92 },
  { id: 'krakow_krowodrza', name: 'Krowodrza', polishName: 'Krowodrza', coefficient: 0.98 },
];

// ============================================================================
// DZIELNICE WROCŁAWIA
// ============================================================================

const WROCLAW_DISTRICTS: WarszawaDistrict[] = [
  { id: 'wroclaw_stare_miasto', name: 'Stare Miasto', polishName: 'Stare Miasto', coefficient: 1.08 },
  { id: 'wroclaw_psie_pole', name: 'Psie Pole', polishName: 'Psie Pole', coefficient: 0.95 },
  { id: 'wroclaw_przedmiescie', name: 'Przedmieście', polishName: 'Przedmieście', coefficient: 0.90 },
  { id: 'wroclaw_fabryczna', name: 'Fabryczna', polishName: 'Fabryczna', coefficient: 0.92 },
];

// ============================================================================
// LISTA MIAST POLSKI
// ============================================================================

export const CITIES: CityData[] = [
  // ======================== MIASTA METROPOLIE ========================
  {
    id: 'gdansk',
    name: 'Gdańsk',
    slug: 'gdansk',
    voivodeship: 'Pomorskie',
    population: 488106,
    category: 'metropolis',
    coefficient: 1.10,
  },
  {
    id: 'krakow',
    name: 'Kraków',
    slug: 'krakow',
    voivodeship: 'Małopolskie',
    population: 804237,
    category: 'metropolis',
    coefficient: 1.15,
    districts: KRAKOW_DISTRICTS,
  },
  {
    id: 'poznan',
    name: 'Poznań',
    slug: 'poznan',
    voivodeship: 'Wielkopolskie',
    population: 534813,
    category: 'metropolis',
    coefficient: 1.10,
  },
  {
    id: 'warszawa',
    name: 'Warszawa',
    slug: 'warszawa',
    voivodeship: 'Mazowieckie',
    population: 863700,
    category: 'metropolis',
    coefficient: 1.25,
    districts: WARSAW_DISTRICTS,
  },
  {
    id: 'wroclaw',
    name: 'Wrocław',
    slug: 'wroclaw',
    voivodeship: 'Dolnośląskie',
    population: 671648,
    category: 'metropolis',
    coefficient: 1.12,
    districts: WROCLAW_DISTRICTS,
  },
  {
    id: 'lodz',
    name: 'Łódź',
    slug: 'lodz',
    voivodeship: 'Łódzkie',
    population: 696127,
    category: 'metropolis',
    coefficient: 1.08,
  },

  // ======================== MIASTA DUŻE ========================
  {
    id: 'belchatow',
    name: 'Bełchatów',
    slug: 'belchatow',
    voivodeship: 'Łódzkie',
    population: 60230,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'bialystok',
    name: 'Białystok',
    slug: 'bialystok',
    voivodeship: 'Podlaskie',
    population: 292700,
    category: 'large',
    coefficient: 1.02,
  },
  {
    id: 'bielsko-biala',
    name: 'Bielsko-Biała',
    slug: 'bielsko-biala',
    voivodeship: 'Śląskie',
    population: 168991,
    category: 'large',
    coefficient: 1.05,
  },
  {
    id: 'busko-zdroj',
    name: 'Busko-Zdrój',
    slug: 'busko-zdroj',
    voivodeship: 'Świętokrzyskie',
    population: 28560,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'bydgoszcz',
    name: 'Bydgoszcz',
    slug: 'bydgoszcz',
    voivodeship: 'Kujawsko-Pomorskie',
    population: 360891,
    category: 'large',
    coefficient: 1.00,
  },
  {
    id: 'bytom',
    name: 'Bytom',
    slug: 'bytom',
    voivodeship: 'Śląskie',
    population: 170506,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'chelm',
    name: 'Chełm',
    slug: 'chelm',
    voivodeship: 'Lubelskie',
    population: 63635,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'chorzow',
    name: 'Chorzów',
    slug: 'chorzow',
    voivodeship: 'Śląskie',
    population: 112007,
    category: 'large',
    coefficient: 1.03,
  },
  {
    id: 'czestochowa',
    name: 'Częstochowa',
    slug: 'czestochowa',
    voivodeship: 'Śląskie',
    population: 222098,
    category: 'large',
    coefficient: 1.02,
  },
  {
    id: 'dabrowa-gornicza',
    name: 'Dąbrowa Górnicza',
    slug: 'dabrowa-gornicza',
    voivodeship: 'Śląskie',
    population: 123790,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'elblag',
    name: 'Elbląg',
    slug: 'elblag',
    voivodeship: 'Warmińsko-Mazurskie',
    population: 119236,
    category: 'large',
    coefficient: 1.02,
  },
  {
    id: 'gdynia',
    name: 'Gdynia',
    slug: 'gdynia',
    voivodeship: 'Pomorskie',
    population: 246316,
    category: 'large',
    coefficient: 1.08,
  },
  {
    id: 'gliwice',
    name: 'Gliwice',
    slug: 'gliwice',
    voivodeship: 'Śląskie',
    population: 175397,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'gniezno',
    name: 'Gniezno',
    slug: 'gniezno',
    voivodeship: 'Wielkopolskie',
    population: 71045,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'gorzow-wielkopolski',
    name: 'Gorzów Wielkopolski',
    slug: 'gorzow-wielkopolski',
    voivodeship: 'Lubuskie',
    population: 124368,
    category: 'large',
    coefficient: 1.02,
  },
  {
    id: 'grudziadz',
    name: 'Grudziądz',
    slug: 'grudziadz',
    voivodeship: 'Kujawsko-Pomorskie',
    population: 96395,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'inowroclaw',
    name: 'Inowrocław',
    slug: 'inowroclaw',
    voivodeship: 'Kujawsko-Pomorskie',
    population: 73653,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'jaroslaw',
    name: 'Jarosław',
    slug: 'jaroslaw',
    voivodeship: 'Podkarpackie',
    population: 38432,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'jastrzebie-zdroj',
    name: 'Jastrzębie-Zdrój',
    slug: 'jastrzebie-zdroj',
    voivodeship: 'Śląskie',
    population: 90447,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'jelenia-gora',
    name: 'Jelenia Góra',
    slug: 'jelenia-gora',
    voivodeship: 'Dolnośląskie',
    population: 82265,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'kalisz',
    name: 'Kalisz',
    slug: 'kalisz',
    voivodeship: 'Wielkopolskie',
    population: 101547,
    category: 'large',
    coefficient: 1.05,
  },
  {
    id: 'katowice',
    name: 'Katowice',
    slug: 'katowice',
    voivodeship: 'Śląskie',
    population: 286801,
    category: 'large',
    coefficient: 1.08,
  },
  {
    id: 'kielce',
    name: 'Kielce',
    slug: 'kielce',
    voivodeship: 'Świętokrzyskie',
    population: 200769,
    category: 'large',
    coefficient: 1.02,
  },
  {
    id: 'konin',
    name: 'Konin',
    slug: 'konin',
    voivodeship: 'Wielkopolskie',
    population: 77155,
    category: 'large',
    coefficient: 1.00,
  },
  {
    id: 'koszalin',
    name: 'Koszalin',
    slug: 'koszalin',
    voivodeship: 'Zachodniopomorskie',
    population: 107901,
    category: 'large',
    coefficient: 1.02,
  },
  {
    id: 'krosno',
    name: 'Krosno',
    slug: 'krosno',
    voivodeship: 'Podkarpackie',
    population: 46300,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'legnica',
    name: 'Legnica',
    slug: 'legnica',
    voivodeship: 'Dolnośląskie',
    population: 103625,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'leszno',
    name: 'Leszno',
    slug: 'leszno',
    voivodeship: 'Wielkopolskie',
    population: 63120,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'lublin',
    name: 'Lublin',
    slug: 'lublin',
    voivodeship: 'Lubelskie',
    population: 335315,
    category: 'large',
    coefficient: 1.00,
  },
  {
    id: 'malbork',
    name: 'Malbork',
    slug: 'malbork',
    voivodeship: 'Pomorskie',
    population: 38765,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'mielec',
    name: 'Mielec',
    slug: 'mielec',
    voivodeship: 'Podkarpackie',
    population: 59969,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'nowy-sacz',
    name: 'Nowy Sącz',
    slug: 'nowy-sacz',
    voivodeship: 'Małopolskie',
    population: 87654,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'olsztyn',
    name: 'Olsztyn',
    slug: 'olsztyn',
    voivodeship: 'Warmińsko-Mazurskie',
    population: 120639,
    category: 'large',
    coefficient: 1.02,
  },
  {
    id: 'opole',
    name: 'Opole',
    slug: 'opole',
    voivodeship: 'Opolskie',
    population: 127755,
    category: 'large',
    coefficient: 1.02,
  },
  {
    id: 'ostrowiec-swietokrzyski',
    name: 'Ostrowiec Świętokrzyski',
    slug: 'ostrowiec-swietokrzyski',
    voivodeship: 'Świętokrzyskie',
    population: 70450,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'pabianice',
    name: 'Pabianice',
    slug: 'pabianice',
    voivodeship: 'Łódzkie',
    population: 68900,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'piotrkow-trybunalski',
    name: 'Piotrków Trybunalski',
    slug: 'piotrkow-trybunalski',
    voivodeship: 'Łódzkie',
    population: 70567,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'pila',
    name: 'Piła',
    slug: 'pila',
    voivodeship: 'Wielkopolskie',
    population: 73400,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'przemysl',
    name: 'Przemyśl',
    slug: 'przemysl',
    voivodeship: 'Podkarpackie',
    population: 36877,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'puck',
    name: 'Puck',
    slug: 'puck',
    voivodeship: 'Pomorskie',
    population: 35896,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'plock',
    name: 'Płock',
    slug: 'plock',
    voivodeship: 'Mazowieckie',
    population: 117576,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'radom',
    name: 'Radom',
    slug: 'radom',
    voivodeship: 'Mazowieckie',
    population: 214833,
    category: 'large',
    coefficient: 1.00,
  },
  {
    id: 'ruda-slaska',
    name: 'Ruda Śląska',
    slug: 'ruda-slaska',
    voivodeship: 'Śląskie',
    population: 139893,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'rybnik',
    name: 'Rybnik',
    slug: 'rybnik',
    voivodeship: 'Śląskie',
    population: 135486,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'rzeszow',
    name: 'Rzeszów',
    slug: 'rzeszow',
    voivodeship: 'Podkarpackie',
    population: 196146,
    category: 'large',
    coefficient: 1.02,
  },
  {
    id: 'skarzysko-kamienna',
    name: 'Skarżysko-Kamienna',
    slug: 'skarzysko-kamienna',
    voivodeship: 'Świętokrzyskie',
    population: 47850,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'skierniewice',
    name: 'Skierniewice',
    slug: 'skierniewice',
    voivodeship: 'Łódzkie',
    population: 25000,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'sopot',
    name: 'Sopot',
    slug: 'sopot',
    voivodeship: 'Pomorskie',
    population: 38236,
    category: 'large',
    coefficient: 1.12,
  },
  {
    id: 'sosnowiec',
    name: 'Sosnowiec',
    slug: 'sosnowiec',
    voivodeship: 'Śląskie',
    population: 214285,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'stalowa-wola',
    name: 'Stalowa Wola',
    slug: 'stalowa-wola',
    voivodeship: 'Podkarpackie',
    population: 63948,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'starogard-gdanski',
    name: 'Starogard Gdański',
    slug: 'starogard-gdanski',
    voivodeship: 'Pomorskie',
    population: 47800,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'suwalki',
    name: 'Suwałki',
    slug: 'suwalki',
    voivodeship: 'Podlaskie',
    population: 69413,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'szczecin',
    name: 'Szczecin',
    slug: 'szczecin',
    voivodeship: 'Zachodniopomorskie',
    population: 398627,
    category: 'large',
    coefficient: 1.05,
  },
  {
    id: 'slupsk',
    name: 'Słupsk',
    slug: 'slupsk',
    voivodeship: 'Pomorskie',
    population: 96388,
    category: 'large',
    coefficient: 1.02,
  },
  {
    id: 'tarnow',
    name: 'Tarnów',
    slug: 'tarnow',
    voivodeship: 'Małopolskie',
    population: 109400,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'tczew',
    name: 'Tczew',
    slug: 'tczew',
    voivodeship: 'Pomorskie',
    population: 60489,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'tomaszow-mazowiecki',
    name: 'Tomaszów Mazowiecki',
    slug: 'tomaszow-mazowiecki',
    voivodeship: 'Łódzkie',
    population: 64230,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'torun',
    name: 'Toruń',
    slug: 'torun',
    voivodeship: 'Kujawsko-Pomorskie',
    population: 200564,
    category: 'large',
    coefficient: 1.05,
  },
  {
    id: 'tychy',
    name: 'Tychy',
    slug: 'tychy',
    voivodeship: 'Śląskie',
    population: 128234,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'walbrzych',
    name: 'Wałbrzych',
    slug: 'walbrzych',
    voivodeship: 'Dolnośląskie',
    population: 117797,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'wejherowo',
    name: 'Wejherowo',
    slug: 'wejherowo',
    voivodeship: 'Pomorskie',
    population: 47239,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'wloclawek',
    name: 'Włocławek',
    slug: 'wloclawek',
    voivodeship: 'Kujawsko-Pomorskie',
    population: 119700,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'zabrze',
    name: 'Zabrze',
    slug: 'zabrze',
    voivodeship: 'Śląskie',
    population: 168628,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'zamosc',
    name: 'Zamość',
    slug: 'zamosc',
    voivodeship: 'Lubelskie',
    population: 64000,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'zdunska-wola',
    name: 'Zduńska Wola',
    slug: 'zdunska-wola',
    voivodeship: 'Łódzkie',
    population: 43120,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'zgierz',
    name: 'Zgierz',
    slug: 'zgierz',
    voivodeship: 'Łódzkie',
    population: 61450,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'zielona-gora',
    name: 'Zielona Góra',
    slug: 'zielona-gora',
    voivodeship: 'Lubuskie',
    population: 140151,
    category: 'large',
    coefficient: 1.02,
  },
  {
    id: 'lomza',
    name: 'Łomża',
    slug: 'lomza',
    voivodeship: 'Podlaskie',
    population: 60623,
    category: 'large',
    coefficient: 1.01,
  },
  {
    id: 'leczna',
    name: 'Łęczna',
    slug: 'leczna',
    voivodeship: 'Lubelskie',
    population: 60000,
    category: 'large',
    coefficient: 1.01,
  },

  // ======================== MIASTA ŚREDNIE ========================
  {
    id: 'biala-podlaska',
    name: 'Biała Podlaska',
    slug: 'biala-podlaska',
    voivodeship: 'Lubelskie',
    population: 56780,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'bedzin',
    name: 'Będzin',
    slug: 'bedzin',
    voivodeship: 'Śląskie',
    population: 59590,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'chrzanow',
    name: 'Chrzanów',
    slug: 'chrzanow',
    voivodeship: 'Małopolskie',
    population: 43780,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'elk',
    name: 'Ełk',
    slug: 'elk',
    voivodeship: 'Warmińsko-Mazurskie',
    population: 60345,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'gostynin',
    name: 'Gostynin',
    slug: 'gostynin',
    voivodeship: 'Mazowieckie',
    population: 43120,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'jaworzno',
    name: 'Jaworzno',
    slug: 'jaworzno',
    voivodeship: 'Śląskie',
    population: 88240,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'kolobrzeg',
    name: 'Kołobrzeg',
    slug: 'kolobrzeg',
    voivodeship: 'Zachodniopomorskie',
    population: 46300,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'kedzierzyn-kozle',
    name: 'Kędzierzyn-Koźle',
    slug: 'kedzierzyn-kozle',
    voivodeship: 'Opolskie',
    population: 53670,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'legionowo',
    name: 'Legionowo',
    slug: 'legionowo',
    voivodeship: 'Mazowieckie',
    population: 58900,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'lebork',
    name: 'Lębork',
    slug: 'lebork',
    voivodeship: 'Pomorskie',
    population: 42076,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'myslowice',
    name: 'Mysłowice',
    slug: 'myslowice',
    voivodeship: 'Śląskie',
    population: 74630,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'nysa',
    name: 'Nysa',
    slug: 'nysa',
    voivodeship: 'Opolskie',
    population: 46120,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'ostroda',
    name: 'Ostróda',
    slug: 'ostroda',
    voivodeship: 'Warmińsko-Mazurskie',
    population: 43560,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'otwock',
    name: 'Otwock',
    slug: 'otwock',
    voivodeship: 'Mazowieckie',
    population: 44560,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'oswiecim',
    name: 'Oświęcim',
    slug: 'oswiecim',
    voivodeship: 'Małopolskie',
    population: 40568,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'piekary-slaskie',
    name: 'Piekary Śląskie',
    slug: 'piekary-slaskie',
    voivodeship: 'Śląskie',
    population: 55670,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'police',
    name: 'Police',
    slug: 'police',
    voivodeship: 'Zachodniopomorskie',
    population: 48900,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'pruszkow',
    name: 'Pruszków',
    slug: 'pruszkow',
    voivodeship: 'Mazowieckie',
    population: 56700,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'pulawy',
    name: 'Puławy',
    slug: 'pulawy',
    voivodeship: 'Lubelskie',
    population: 49870,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'raciborz',
    name: 'Racibórz',
    slug: 'raciborz',
    voivodeship: 'Śląskie',
    population: 56790,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'radomsko',
    name: 'Radomsko',
    slug: 'radomsko',
    voivodeship: 'Łódzkie',
    population: 43780,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'siemianowice-slaskie',
    name: 'Siemianowice Śląskie',
    slug: 'siemianowice-slaskie',
    voivodeship: 'Śląskie',
    population: 66450,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'sieradz',
    name: 'Sieradz',
    slug: 'sieradz',
    voivodeship: 'Łódzkie',
    population: 43230,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'stargard',
    name: 'Stargard',
    slug: 'stargard',
    voivodeship: 'Zachodniopomorskie',
    population: 68900,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'tarnobrzeg',
    name: 'Tarnobrzeg',
    slug: 'tarnobrzeg',
    voivodeship: 'Podkarpackie',
    population: 50589,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'tarnowskie-gory',
    name: 'Tarnowskie Góry',
    slug: 'tarnowskie-gory',
    voivodeship: 'Śląskie',
    population: 58970,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'wodzislaw-slaski',
    name: 'Wodzisław Śląski',
    slug: 'wodzislaw-slaski',
    voivodeship: 'Śląskie',
    population: 51932,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'wolomin',
    name: 'Wołomin',
    slug: 'wolomin',
    voivodeship: 'Mazowieckie',
    population: 51230,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'zawiercie',
    name: 'Zawiercie',
    slug: 'zawiercie',
    voivodeship: 'Śląskie',
    population: 48900,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'swinoujscie',
    name: 'Świnoujście',
    slug: 'swinoujscie',
    voivodeship: 'Zachodniopomorskie',
    population: 41300,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'swietochlowice',
    name: 'Świętochłowice',
    slug: 'swietochlowice',
    voivodeship: 'Śląskie',
    population: 52890,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'zagan',
    name: 'Żagań',
    slug: 'zagan',
    voivodeship: 'Lubuskie',
    population: 47890,
    category: 'medium',
    coefficient: 0.98,
  },
  {
    id: 'zory',
    name: 'Żory',
    slug: 'zory',
    voivodeship: 'Śląskie',
    population: 57230,
    category: 'medium',
    coefficient: 0.98,
  },

  // ======================== MIASTA MAŁE ========================
  {
    id: 'aleksandrow-kujawski',
    name: 'Aleksandrów Kujawski',
    slug: 'aleksandrow-kujawski',
    voivodeship: 'Kujawsko-Pomorskie',
    population: 15600,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'augustow',
    name: 'Augustów',
    slug: 'augustow',
    voivodeship: 'Podlaskie',
    population: 30110,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'bartoszyce',
    name: 'Bartoszyce',
    slug: 'bartoszyce',
    voivodeship: 'Warmińsko-Mazurskie',
    population: 24000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'bialobrzegi',
    name: 'Białobrzegi',
    slug: 'bialobrzegi',
    voivodeship: 'Mazowieckie',
    population: 4560,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'bialogard',
    name: 'Białogard',
    slug: 'bialogard',
    voivodeship: 'Zachodniopomorskie',
    population: 29780,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'bielsk-podlaski',
    name: 'Bielsk Podlaski',
    slug: 'bielsk-podlaski',
    voivodeship: 'Podlaskie',
    population: 26340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'bilgoraj',
    name: 'Biłgoraj',
    slug: 'bilgoraj',
    voivodeship: 'Lubelskie',
    population: 27450,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'bochnia',
    name: 'Bochnia',
    slug: 'bochnia',
    voivodeship: 'Małopolskie',
    population: 28700,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'boleslawiec',
    name: 'Bolesławiec',
    slug: 'boleslawiec',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'braniewo',
    name: 'Braniewo',
    slug: 'braniewo',
    voivodeship: 'Warmińsko-Mazurskie',
    population: 16570,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'brodnica',
    name: 'Brodnica',
    slug: 'brodnica',
    voivodeship: 'Kujawsko-Pomorskie',
    population: 22600,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'brzeg',
    name: 'Brzeg',
    slug: 'brzeg',
    voivodeship: 'Opolskie',
    population: 35780,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'brzesko',
    name: 'Brzesko',
    slug: 'brzesko',
    voivodeship: 'Małopolskie',
    population: 17100,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'brzeziny',
    name: 'Brzeziny',
    slug: 'brzeziny',
    voivodeship: 'Łódzkie',
    population: 13450,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'brzozow',
    name: 'Brzozów',
    slug: 'brzozow',
    voivodeship: 'Podkarpackie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'bytow',
    name: 'Bytów',
    slug: 'bytow',
    voivodeship: 'Pomorskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'chelmno',
    name: 'Chełmno',
    slug: 'chelmno',
    voivodeship: 'Kujawsko-Pomorskie',
    population: 19567,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'chodziez',
    name: 'Chodzież',
    slug: 'chodziez',
    voivodeship: 'Wielkopolskie',
    population: 13560,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'chojnice',
    name: 'Chojnice',
    slug: 'chojnice',
    voivodeship: 'Pomorskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'choszczno',
    name: 'Choszczno',
    slug: 'choszczno',
    voivodeship: 'Zachodniopomorskie',
    population: 14560,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'ciechanow',
    name: 'Ciechanów',
    slug: 'ciechanow',
    voivodeship: 'Mazowieckie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'cieszyn',
    name: 'Cieszyn',
    slug: 'cieszyn',
    voivodeship: 'Śląskie',
    population: 35750,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'czarnkow',
    name: 'Czarnków',
    slug: 'czarnkow',
    voivodeship: 'Wielkopolskie',
    population: 18900,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'czluchow',
    name: 'Człuchów',
    slug: 'czluchow',
    voivodeship: 'Pomorskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'drawsko-pomorskie',
    name: 'Drawsko Pomorskie',
    slug: 'drawsko-pomorskie',
    voivodeship: 'Zachodniopomorskie',
    population: 8900,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'dzialdowo',
    name: 'Działdowo',
    slug: 'dzialdowo',
    voivodeship: 'Warmińsko-Mazurskie',
    population: 16780,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'dzierzoniow',
    name: 'Dzierżoniów',
    slug: 'dzierzoniow',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'dabrowa-tarnowska',
    name: 'Dąbrowa Tarnowska',
    slug: 'dabrowa-tarnowska',
    voivodeship: 'Małopolskie',
    population: 18900,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'debica',
    name: 'Dębica',
    slug: 'debica',
    voivodeship: 'Podkarpackie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'garwolin',
    name: 'Garwolin',
    slug: 'garwolin',
    voivodeship: 'Mazowieckie',
    population: 29450,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'gizycko',
    name: 'Giżycko',
    slug: 'gizycko',
    voivodeship: 'Warmińsko-Mazurskie',
    population: 29500,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'goleniow',
    name: 'Goleniów',
    slug: 'goleniow',
    voivodeship: 'Zachodniopomorskie',
    population: 12340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'golub-dobrzyn',
    name: 'Golub-Dobrzyń',
    slug: 'golub-dobrzyn',
    voivodeship: 'Kujawsko-Pomorskie',
    population: 8956,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'gorlice',
    name: 'Gorlice',
    slug: 'gorlice',
    voivodeship: 'Małopolskie',
    population: 32654,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'gostyn',
    name: 'Gostyń',
    slug: 'gostyn',
    voivodeship: 'Wielkopolskie',
    population: 30560,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'grajewo',
    name: 'Grajewo',
    slug: 'grajewo',
    voivodeship: 'Podlaskie',
    population: 28900,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'grodzisk-mazowiecki',
    name: 'Grodzisk Mazowiecki',
    slug: 'grodzisk-mazowiecki',
    voivodeship: 'Mazowieckie',
    population: 20340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'grodzisk-wielkopolski',
    name: 'Grodzisk Wielkopolski',
    slug: 'grodzisk-wielkopolski',
    voivodeship: 'Wielkopolskie',
    population: 23450,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'gryfice',
    name: 'Gryfice',
    slug: 'gryfice',
    voivodeship: 'Zachodniopomorskie',
    population: 28450,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'gryfino',
    name: 'Gryfino',
    slug: 'gryfino',
    voivodeship: 'Zachodniopomorskie',
    population: 22340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'grojec',
    name: 'Grójec',
    slug: 'grojec',
    voivodeship: 'Mazowieckie',
    population: 31230,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'gora',
    name: 'Góra',
    slug: 'gora',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'glogow',
    name: 'Głogów',
    slug: 'glogow',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'glubczyce',
    name: 'Głubczyce',
    slug: 'glubczyce',
    voivodeship: 'Opolskie',
    population: 19870,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'hajnowka',
    name: 'Hajnówka',
    slug: 'hajnowka',
    voivodeship: 'Podlaskie',
    population: 22100,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'hrubieszow',
    name: 'Hrubieszów',
    slug: 'hrubieszow',
    voivodeship: 'Lubelskie',
    population: 18560,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'ilawa',
    name: 'Iława',
    slug: 'ilawa',
    voivodeship: 'Warmińsko-Mazurskie',
    population: 31456,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'janow-lubelski',
    name: 'Janów Lubelski',
    slug: 'janow-lubelski',
    voivodeship: 'Lubelskie',
    population: 12340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'jarocin',
    name: 'Jarocin',
    slug: 'jarocin',
    voivodeship: 'Wielkopolskie',
    population: 27340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'jaslo',
    name: 'Jasło',
    slug: 'jaslo',
    voivodeship: 'Podkarpackie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'jawor',
    name: 'Jawor',
    slug: 'jawor',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'jedrzejow',
    name: 'Jędrzejów',
    slug: 'jedrzejow',
    voivodeship: 'Świętokrzyskie',
    population: 17450,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'kamienna-gora',
    name: 'Kamienna Góra',
    slug: 'kamienna-gora',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'kamien-pomorski',
    name: 'Kamień Pomorski',
    slug: 'kamien-pomorski',
    voivodeship: 'Zachodniopomorskie',
    population: 8560,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'kartuzy',
    name: 'Kartuzy',
    slug: 'kartuzy',
    voivodeship: 'Pomorskie',
    population: 18900,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'kazimierza-wielka',
    name: 'Kazimierza Wielka',
    slug: 'kazimierza-wielka',
    voivodeship: 'Świętokrzyskie',
    population: 7890,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'kluczbork',
    name: 'Kluczbork',
    slug: 'kluczbork',
    voivodeship: 'Opolskie',
    population: 18560,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'kolbuszowa',
    name: 'Kolbuszowa',
    slug: 'kolbuszowa',
    voivodeship: 'Podkarpackie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'kolno',
    name: 'Kolno',
    slug: 'kolno',
    voivodeship: 'Podlaskie',
    population: 9340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'kozienice',
    name: 'Kozienice',
    slug: 'kozienice',
    voivodeship: 'Mazowieckie',
    population: 18900,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'kolo',
    name: 'Koło',
    slug: 'kolo',
    voivodeship: 'Wielkopolskie',
    population: 30450,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'konskie',
    name: 'Końskie',
    slug: 'konskie',
    voivodeship: 'Świętokrzyskie',
    population: 22340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'koscian',
    name: 'Kościan',
    slug: 'koscian',
    voivodeship: 'Wielkopolskie',
    population: 21560,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'koscierzyna',
    name: 'Kościerzyna',
    slug: 'koscierzyna',
    voivodeship: 'Pomorskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'krapkowice',
    name: 'Krapkowice',
    slug: 'krapkowice',
    voivodeship: 'Opolskie',
    population: 10230,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'krasnystaw',
    name: 'Krasnystaw',
    slug: 'krasnystaw',
    voivodeship: 'Lubelskie',
    population: 20560,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'krasnik',
    name: 'Kraśnik',
    slug: 'krasnik',
    voivodeship: 'Lubelskie',
    population: 18900,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'krosno-odrzanskie',
    name: 'Krosno Odrzańskie',
    slug: 'krosno-odrzanskie',
    voivodeship: 'Lubuskie',
    population: 8900,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'krotoszyn',
    name: 'Krotoszyn',
    slug: 'krotoszyn',
    voivodeship: 'Wielkopolskie',
    population: 20100,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'kutno',
    name: 'Kutno',
    slug: 'kutno',
    voivodeship: 'Łódzkie',
    population: 36780,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'kwidzyn',
    name: 'Kwidzyn',
    slug: 'kwidzyn',
    voivodeship: 'Pomorskie',
    population: 36000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'kepno',
    name: 'Kępno',
    slug: 'kepno',
    voivodeship: 'Wielkopolskie',
    population: 15870,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'ketrzyn',
    name: 'Kętrzyn',
    slug: 'ketrzyn',
    voivodeship: 'Warmińsko-Mazurskie',
    population: 27850,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'klobuck',
    name: 'Kłobuck',
    slug: 'klobuck',
    voivodeship: 'Śląskie',
    population: 19800,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'klodzko',
    name: 'Kłodzko',
    slug: 'klodzko',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'lesko',
    name: 'Lesko',
    slug: 'lesko',
    voivodeship: 'Podkarpackie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'lezajsk',
    name: 'Leżajsk',
    slug: 'lezajsk',
    voivodeship: 'Podkarpackie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'lidzbark-warminski',
    name: 'Lidzbark Warmiński',
    slug: 'lidzbark-warminski',
    voivodeship: 'Warmińsko-Mazurskie',
    population: 16340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'limanowa',
    name: 'Limanowa',
    slug: 'limanowa',
    voivodeship: 'Małopolskie',
    population: 14980,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'lipno',
    name: 'Lipno',
    slug: 'lipno',
    voivodeship: 'Kujawsko-Pomorskie',
    population: 10200,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'lipsko',
    name: 'Lipsko',
    slug: 'lipsko',
    voivodeship: 'Mazowieckie',
    population: 7230,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'lubaczow',
    name: 'Lubaczów',
    slug: 'lubaczow',
    voivodeship: 'Podkarpackie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'lubartow',
    name: 'Lubartów',
    slug: 'lubartow',
    voivodeship: 'Lubelskie',
    population: 16560,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'luban',
    name: 'Lubań',
    slug: 'luban',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'lubin',
    name: 'Lubin',
    slug: 'lubin',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'lubliniec',
    name: 'Lubliniec',
    slug: 'lubliniec',
    voivodeship: 'Śląskie',
    population: 25670,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'lwowek-slaski',
    name: 'Lwówek Śląski',
    slug: 'lwowek-slaski',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'makow-mazowiecki',
    name: 'Maków Mazowiecki',
    slug: 'makow-mazowiecki',
    voivodeship: 'Mazowieckie',
    population: 5780,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'miechow',
    name: 'Miechów',
    slug: 'miechow',
    voivodeship: 'Małopolskie',
    population: 12350,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'mikolow',
    name: 'Mikołów',
    slug: 'mikolow',
    voivodeship: 'Śląskie',
    population: 20560,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'milicz',
    name: 'Milicz',
    slug: 'milicz',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'miedzychod',
    name: 'Międzychód',
    slug: 'miedzychod',
    voivodeship: 'Wielkopolskie',
    population: 8900,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'miedzyrzecz',
    name: 'Międzyrzecz',
    slug: 'miedzyrzecz',
    voivodeship: 'Lubuskie',
    population: 18900,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'minsk-mazowiecki',
    name: 'Mińsk Mazowiecki',
    slug: 'minsk-mazowiecki',
    voivodeship: 'Mazowieckie',
    population: 39780,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'mogilno',
    name: 'Mogilno',
    slug: 'mogilno',
    voivodeship: 'Kujawsko-Pomorskie',
    population: 7654,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'monki',
    name: 'Mońki',
    slug: 'monki',
    voivodeship: 'Podlaskie',
    population: 8560,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'mragowo',
    name: 'Mrągowo',
    slug: 'mragowo',
    voivodeship: 'Warmińsko-Mazurskie',
    population: 21340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'myszkow',
    name: 'Myszków',
    slug: 'myszkow',
    voivodeship: 'Śląskie',
    population: 21340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'myslenice',
    name: 'Myślenice',
    slug: 'myslenice',
    voivodeship: 'Małopolskie',
    population: 17250,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'mysliborz',
    name: 'Myślibórz',
    slug: 'mysliborz',
    voivodeship: 'Zachodniopomorskie',
    population: 10230,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'mlawa',
    name: 'Mława',
    slug: 'mlawa',
    voivodeship: 'Mazowieckie',
    population: 24560,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'naklo-nad-notecia',
    name: 'Nakło nad Notecią',
    slug: 'naklo-nad-notecia',
    voivodeship: 'Kujawsko-Pomorskie',
    population: 8750,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'namyslow',
    name: 'Namysłów',
    slug: 'namyslow',
    voivodeship: 'Opolskie',
    population: 11230,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'nidzica',
    name: 'Nidzica',
    slug: 'nidzica',
    voivodeship: 'Warmińsko-Mazurskie',
    population: 19870,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'nisko',
    name: 'Nisko',
    slug: 'nisko',
    voivodeship: 'Podkarpackie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'nowa-sol',
    name: 'Nowa Sól',
    slug: 'nowa-sol',
    voivodeship: 'Lubuskie',
    population: 34560,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'nowe-miasto-lubawskie',
    name: 'Nowe Miasto Lubawskie',
    slug: 'nowe-miasto-lubawskie',
    voivodeship: 'Warmińsko-Mazurskie',
    population: 5670,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'nowy-dwor-gdanski',
    name: 'Nowy Dwór Gdański',
    slug: 'nowy-dwor-gdanski',
    voivodeship: 'Pomorskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'nowy-dwor-mazowiecki',
    name: 'Nowy Dwór Mazowiecki',
    slug: 'nowy-dwor-mazowiecki',
    voivodeship: 'Mazowieckie',
    population: 37450,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'nowy-targ',
    name: 'Nowy Targ',
    slug: 'nowy-targ',
    voivodeship: 'Małopolskie',
    population: 34256,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'nowy-tomysl',
    name: 'Nowy Tomyśl',
    slug: 'nowy-tomysl',
    voivodeship: 'Wielkopolskie',
    population: 28950,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'oborniki',
    name: 'Oborniki',
    slug: 'oborniki',
    voivodeship: 'Wielkopolskie',
    population: 10750,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'olecko',
    name: 'Olecko',
    slug: 'olecko',
    voivodeship: 'Warmińsko-Mazurskie',
    population: 15670,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'olesno',
    name: 'Olesno',
    slug: 'olesno',
    voivodeship: 'Opolskie',
    population: 9870,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'olesnica',
    name: 'Oleśnica',
    slug: 'olesnica',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'olkusz',
    name: 'Olkusz',
    slug: 'olkusz',
    voivodeship: 'Małopolskie',
    population: 24550,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'opatow',
    name: 'Opatów',
    slug: 'opatow',
    voivodeship: 'Świętokrzyskie',
    population: 6450,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'opoczno',
    name: 'Opoczno',
    slug: 'opoczno',
    voivodeship: 'Łódzkie',
    population: 21340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'opole-lubelskie',
    name: 'Opole Lubelskie',
    slug: 'opole-lubelskie',
    voivodeship: 'Lubelskie',
    population: 21340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'ostroleka',
    name: 'Ostrołęka',
    slug: 'ostroleka',
    voivodeship: 'Mazowieckie',
    population: 6780,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'ostrzeszow',
    name: 'Ostrzeszów',
    slug: 'ostrzeszow',
    voivodeship: 'Wielkopolskie',
    population: 15230,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'ostrow-mazowiecki',
    name: 'Ostrów Mazowiecki',
    slug: 'ostrow-mazowiecki',
    voivodeship: 'Mazowieckie',
    population: 22340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'ostrow-wielkopolski',
    name: 'Ostrów Wielkopolski',
    slug: 'ostrow-wielkopolski',
    voivodeship: 'Wielkopolskie',
    population: 28560,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'olawa',
    name: 'Oława',
    slug: 'olawa',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'pajeczno',
    name: 'Pajęczno',
    slug: 'pajeczno',
    voivodeship: 'Łódzkie',
    population: 10230,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'parczew',
    name: 'Parczew',
    slug: 'parczew',
    voivodeship: 'Lubelskie',
    population: 5670,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'piaseczno',
    name: 'Piaseczno',
    slug: 'piaseczno',
    voivodeship: 'Mazowieckie',
    population: 16780,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'pisz',
    name: 'Pisz',
    slug: 'pisz',
    voivodeship: 'Warmińsko-Mazurskie',
    population: 17450,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'pinczow',
    name: 'Pińczów',
    slug: 'pinczow',
    voivodeship: 'Świętokrzyskie',
    population: 17560,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'pleszew',
    name: 'Pleszew',
    slug: 'pleszew',
    voivodeship: 'Wielkopolskie',
    population: 11480,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'poddebice',
    name: 'Poddębice',
    slug: 'poddebice',
    voivodeship: 'Łódzkie',
    population: 11340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'polkowice',
    name: 'Polkowice',
    slug: 'polkowice',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'proszowice',
    name: 'Proszowice',
    slug: 'proszowice',
    voivodeship: 'Małopolskie',
    population: 7890,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'prudnik',
    name: 'Prudnik',
    slug: 'prudnik',
    voivodeship: 'Opolskie',
    population: 24560,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'przasnysz',
    name: 'Przasnysz',
    slug: 'przasnysz',
    voivodeship: 'Mazowieckie',
    population: 20340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'przeworsk',
    name: 'Przeworsk',
    slug: 'przeworsk',
    voivodeship: 'Podkarpackie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'przysucha',
    name: 'Przysucha',
    slug: 'przysucha',
    voivodeship: 'Mazowieckie',
    population: 6780,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'pszczyna',
    name: 'Pszczyna',
    slug: 'pszczyna',
    voivodeship: 'Śląskie',
    population: 22340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'pultusk',
    name: 'Pułtusk',
    slug: 'pultusk',
    voivodeship: 'Mazowieckie',
    population: 8450,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'pyrzyce',
    name: 'Pyrzyce',
    slug: 'pyrzyce',
    voivodeship: 'Zachodniopomorskie',
    population: 13560,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'plonsk',
    name: 'Płońsk',
    slug: 'plonsk',
    voivodeship: 'Mazowieckie',
    population: 19670,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'radziejow',
    name: 'Radziejów',
    slug: 'radziejow',
    voivodeship: 'Kujawsko-Pomorskie',
    population: 11200,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'radzyn-podlaski',
    name: 'Radzyń Podlaski',
    slug: 'radzyn-podlaski',
    voivodeship: 'Lubelskie',
    population: 16780,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'rawa-mazowiecka',
    name: 'Rawa Mazowiecka',
    slug: 'rawa-mazowiecka',
    voivodeship: 'Łódzkie',
    population: 19670,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'rawicz',
    name: 'Rawicz',
    slug: 'rawicz',
    voivodeship: 'Wielkopolskie',
    population: 18890,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'ropczyce',
    name: 'Ropczyce',
    slug: 'ropczyce',
    voivodeship: 'Podkarpackie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'ryki',
    name: 'Ryki',
    slug: 'ryki',
    voivodeship: 'Lubelskie',
    population: 19870,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'rypin',
    name: 'Rypin',
    slug: 'rypin',
    voivodeship: 'Kujawsko-Pomorskie',
    population: 17800,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'sandomierz',
    name: 'Sandomierz',
    slug: 'sandomierz',
    voivodeship: 'Świętokrzyskie',
    population: 25670,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'sanok',
    name: 'Sanok',
    slug: 'sanok',
    voivodeship: 'Podkarpackie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'sejny',
    name: 'Sejny',
    slug: 'sejny',
    voivodeship: 'Podlaskie',
    population: 7890,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'siedlce',
    name: 'Siedlce',
    slug: 'siedlce',
    voivodeship: 'Mazowieckie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'siemiatycze',
    name: 'Siemiatycze',
    slug: 'siemiatycze',
    voivodeship: 'Podlaskie',
    population: 11340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'sierpc',
    name: 'Sierpc',
    slug: 'sierpc',
    voivodeship: 'Mazowieckie',
    population: 16570,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'sochaczew',
    name: 'Sochaczew',
    slug: 'sochaczew',
    voivodeship: 'Mazowieckie',
    population: 38900,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'sokolow-podlaski',
    name: 'Sokołów Podlaski',
    slug: 'sokolow-podlaski',
    voivodeship: 'Mazowieckie',
    population: 10230,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'sokolka',
    name: 'Sokółka',
    slug: 'sokolka',
    voivodeship: 'Podlaskie',
    population: 19570,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'starachowice',
    name: 'Starachowice',
    slug: 'starachowice',
    voivodeship: 'Świętokrzyskie',
    population: 16780,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'staszow',
    name: 'Staszów',
    slug: 'staszow',
    voivodeship: 'Świętokrzyskie',
    population: 15780,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'strzelce-krajenskie',
    name: 'Strzelce Krajeńskie',
    slug: 'strzelce-krajenskie',
    voivodeship: 'Lubuskie',
    population: 5670,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'strzelce-opolskie',
    name: 'Strzelce Opolskie',
    slug: 'strzelce-opolskie',
    voivodeship: 'Opolskie',
    population: 14780,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'strzelin',
    name: 'Strzelin',
    slug: 'strzelin',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'strzyzow',
    name: 'Strzyżów',
    slug: 'strzyzow',
    voivodeship: 'Podkarpackie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'sucha-beskidzka',
    name: 'Sucha Beskidzka',
    slug: 'sucha-beskidzka',
    voivodeship: 'Małopolskie',
    population: 22130,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'sulecin',
    name: 'Sulęcin',
    slug: 'sulecin',
    voivodeship: 'Lubuskie',
    population: 12340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'szamotuly',
    name: 'Szamotuły',
    slug: 'szamotuly',
    voivodeship: 'Wielkopolskie',
    population: 8670,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'szczytno',
    name: 'Szczytno',
    slug: 'szczytno',
    voivodeship: 'Warmińsko-Mazurskie',
    population: 27340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'sztum',
    name: 'Sztum',
    slug: 'sztum',
    voivodeship: 'Pomorskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'szydlowiec',
    name: 'Szydłowiec',
    slug: 'szydlowiec',
    voivodeship: 'Mazowieckie',
    population: 8900,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'sepolno-krajenskie',
    name: 'Sępólno Krajeńskie',
    slug: 'sepolno-krajenskie',
    voivodeship: 'Kujawsko-Pomorskie',
    population: 7200,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'slawno',
    name: 'Sławno',
    slug: 'slawno',
    voivodeship: 'Zachodniopomorskie',
    population: 9870,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'slubice',
    name: 'Słubice',
    slug: 'slubice',
    voivodeship: 'Lubuskie',
    population: 17560,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'slupca',
    name: 'Słupca',
    slug: 'slupca',
    voivodeship: 'Wielkopolskie',
    population: 6250,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'tomaszow-lubelski',
    name: 'Tomaszów Lubelski',
    slug: 'tomaszow-lubelski',
    voivodeship: 'Lubelskie',
    population: 22340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'trzebnica',
    name: 'Trzebnica',
    slug: 'trzebnica',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'tuchola',
    name: 'Tuchola',
    slug: 'tuchola',
    voivodeship: 'Kujawsko-Pomorskie',
    population: 8900,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'turek',
    name: 'Turek',
    slug: 'turek',
    voivodeship: 'Wielkopolskie',
    population: 17850,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'ustrzyki-dolne',
    name: 'Ustrzyki Dolne',
    slug: 'ustrzyki-dolne',
    voivodeship: 'Podkarpackie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'wadowice',
    name: 'Wadowice',
    slug: 'wadowice',
    voivodeship: 'Małopolskie',
    population: 30160,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'walcz',
    name: 'Wałcz',
    slug: 'walcz',
    voivodeship: 'Zachodniopomorskie',
    population: 17340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'wieliczka',
    name: 'Wieliczka',
    slug: 'wieliczka',
    voivodeship: 'Małopolskie',
    population: 24570,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'wielun',
    name: 'Wieluń',
    slug: 'wielun',
    voivodeship: 'Łódzkie',
    population: 19670,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'wieruszow',
    name: 'Wieruszów',
    slug: 'wieruszow',
    voivodeship: 'Łódzkie',
    population: 10450,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'wolsztyn',
    name: 'Wolsztyn',
    slug: 'wolsztyn',
    voivodeship: 'Wielkopolskie',
    population: 7650,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'wolow',
    name: 'Wołów',
    slug: 'wolow',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'wrzesnia',
    name: 'Września',
    slug: 'wrzesnia',
    voivodeship: 'Wielkopolskie',
    population: 19100,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'wschowa',
    name: 'Wschowa',
    slug: 'wschowa',
    voivodeship: 'Lubuskie',
    population: 15670,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'wysokie-mazowieckie',
    name: 'Wysokie Mazowieckie',
    slug: 'wysokie-mazowieckie',
    voivodeship: 'Podlaskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'wyszkow',
    name: 'Wyszków',
    slug: 'wyszkow',
    voivodeship: 'Mazowieckie',
    population: 23450,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'wabrzezno',
    name: 'Wąbrzeźno',
    slug: 'wabrzezno',
    voivodeship: 'Kujawsko-Pomorskie',
    population: 8500,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'wagrowiec',
    name: 'Wągrowiec',
    slug: 'wagrowiec',
    voivodeship: 'Wielkopolskie',
    population: 18340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'wegorzewo',
    name: 'Węgorzewo',
    slug: 'wegorzewo',
    voivodeship: 'Warmińsko-Mazurskie',
    population: 11230,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'wegrow',
    name: 'Węgrów',
    slug: 'wegrow',
    voivodeship: 'Mazowieckie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'wlodawa',
    name: 'Włodawa',
    slug: 'wlodawa',
    voivodeship: 'Lubelskie',
    population: 3456,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'wloszczowa',
    name: 'Włoszczowa',
    slug: 'wloszczowa',
    voivodeship: 'Świętokrzyskie',
    population: 13230,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'zakopane',
    name: 'Zakopane',
    slug: 'zakopane',
    voivodeship: 'Małopolskie',
    population: 27352,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'zambrow',
    name: 'Zambrów',
    slug: 'zambrow',
    voivodeship: 'Podlaskie',
    population: 18340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'zgorzelec',
    name: 'Zgorzelec',
    slug: 'zgorzelec',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'zwolen',
    name: 'Zwoleń',
    slug: 'zwolen',
    voivodeship: 'Mazowieckie',
    population: 3450,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'zabkowice-slaskie',
    name: 'Ząbkowice Śląskie',
    slug: 'zabkowice-slaskie',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'zlotoryja',
    name: 'Złotoryja',
    slug: 'zlotoryja',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'zlotow',
    name: 'Złotów',
    slug: 'zlotow',
    voivodeship: 'Wielkopolskie',
    population: 15670,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'lask',
    name: 'Łask',
    slug: 'lask',
    voivodeship: 'Łódzkie',
    population: 18900,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'lancut',
    name: 'Łańcut',
    slug: 'lancut',
    voivodeship: 'Podkarpackie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'lobez',
    name: 'Łobez',
    slug: 'lobez',
    voivodeship: 'Zachodniopomorskie',
    population: 7890,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'losice',
    name: 'Łosice',
    slug: 'losice',
    voivodeship: 'Mazowieckie',
    population: 5670,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'lowicz',
    name: 'Łowicz',
    slug: 'lowicz',
    voivodeship: 'Łódzkie',
    population: 29450,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'lukow',
    name: 'Łuków',
    slug: 'lukow',
    voivodeship: 'Lubelskie',
    population: 20340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'leczyca',
    name: 'Łęczyca',
    slug: 'leczyca',
    voivodeship: 'Łódzkie',
    population: 19340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'srem',
    name: 'Śrem',
    slug: 'srem',
    voivodeship: 'Wielkopolskie',
    population: 19780,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'sroda-wielkopolska',
    name: 'Środa Wielkopolska',
    slug: 'sroda-wielkopolska',
    voivodeship: 'Wielkopolskie',
    population: 17520,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'sroda-slaska',
    name: 'Środa Śląska',
    slug: 'sroda-slaska',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'swidnica',
    name: 'Świdnica',
    slug: 'swidnica',
    voivodeship: 'Dolnośląskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'swidnik',
    name: 'Świdnik',
    slug: 'swidnik',
    voivodeship: 'Lubelskie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'swidwin',
    name: 'Świdwin',
    slug: 'swidwin',
    voivodeship: 'Zachodniopomorskie',
    population: 15780,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'swiebodzin',
    name: 'Świebodzin',
    slug: 'swiebodzin',
    voivodeship: 'Lubuskie',
    population: 21340,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'swiecie',
    name: 'Świecie',
    slug: 'swiecie',
    voivodeship: 'Kujawsko-Pomorskie',
    population: 26500,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'zary',
    name: 'Żary',
    slug: 'zary',
    voivodeship: 'Lubuskie',
    population: 39230,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'znin',
    name: 'Żnin',
    slug: 'znin',
    voivodeship: 'Kujawsko-Pomorskie',
    population: 19850,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'zuromin',
    name: 'Żuromin',
    slug: 'zuromin',
    voivodeship: 'Mazowieckie',
    population: 7120,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'zyrardow',
    name: 'Żyrardów',
    slug: 'zyrardow',
    voivodeship: 'Mazowieckie',
    population: 25000,
    category: 'small',
    coefficient: 0.85,
  },
  {
    id: 'zywiec',
    name: 'Żywiec',
    slug: 'zywiec',
    voivodeship: 'Śląskie',
    population: 32540,
    category: 'small',
    coefficient: 0.85,
  },
];

// ============================================================================
// FUNKCJE POMOCNICZE
// ============================================================================

/**
 * Pobiera dane miasta po ID
 */
export function getCityById(cityId: string): CityData | undefined {
  return CITIES.find((c) => c.id === cityId);
}

/**
 * Pobiera dane miasta po nazwie
 */
export function getCityByName(cityName: string): CityData | undefined {
  return CITIES.find((c) => c.name.toLowerCase() === cityName.toLowerCase());
}

/**
 * Pobiera dane miasta po sługu
 */
export function getCityBySlug(slug: string): CityData | undefined {
  return CITIES.find((c) => c.slug === slug);
}

/**
 * Pobiera listę dzielnic dla miasta
 */
export function getDistricts(cityId: string): WarszawaDistrict[] | undefined {
  const city = getCityById(cityId);
  return city?.districts;
}

/**
 * Pobiera współczynnik dzielnicy
 */
export function getDistrictCoefficient(cityId: string, districtId: string): number | undefined {
  const districts = getDistricts(cityId);
  if (!districts) return undefined;

  const district = districts.find((d) => d.id === districtId);
  return district?.coefficient;
}

/**
 * Pobiera wszystkie miasta z kategorią
 */
export function getCitiesByCategory(category: CityCategory): CityData[] {
  return CITIES.filter((c) => c.category === category);
}

/**
 * Pobiera wszystkie miasta z województwa
 */
export function getCitiesByVoivodeship(voivodeship: string): CityData[] {
  return CITIES.filter((c) => c.voivodeship === voivodeship);
}

/**
 * Sortuje miasta alfabetycznie
 */
export function sortCities(cities: CityData[]): CityData[] {
  return [...cities].sort((a, b) => a.name.localeCompare(b.name, 'pl'));
}

/**
 * Pobiera miasto alternatywne gdy podane nie istnieje
 */
export function getFallbackCity(cityId: string): CityData {
  const city = getCityById(cityId);
  if (city) return city;

  // Fallback do kategorii miasta
  const smallCities = getCitiesByCategory('small');
  return smallCities[0] || CITIES[0];
}

/**
 * Pobiera wszystkie miasta
 */
export function getAllCities(): CityData[] {
  return CITIES;
}
